server:
  port: ${PORT:8761}
management:
  port: ${MGMTPORT:8763}
  context_path: /admin
  security:
    enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0



#eureka:
#  instance:
#    hostname: localhost
#  metadataMap:
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    server:
#      waitTimeInMsWhenSyncEmpty: 0
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  dashboard:
#    path: /eurekawebui