spring:
    profiles: default
    application:
#      admin:
#        enabled: true
      name: receiver

server:
  port: ${PORT:8081}

management:
  security:
    enabled: false
  port: ${MGMTPORT:8089}

endpoints:
  hypermedia:
    enabled: true
